### ISSUE TITLE
[Bug]: License Miss-match

### ISSUE THREAD

**Issue by fsmeier** [valantic-CEC-Deutschland-GmbH/spryker-kit-intellij-plugin#31]
### Contact Details

florian.schwarzmeier@spryker.com

### What happened?

Heyhey,

in the description of https://plugins.jetbrains.com/plugin/18766-sprykerkit it is mentioned that its MIT license, but here its marked as Apache-2.0 license. Not sure if this can be in parallel. 

All the best,
Florian 

### Version

1.0.0

**Comment by patrickjaja** [comment]
Thanks for heads-up, its fixed
